db_host: 'localhost'
db_name: 'cursosLivres'
db_user: 'cursosLivres'
db_pw: 'cursosLivres123' #senha
django_secret_key: 'secretissimo123456'
debug_mode: True
email_sistema: 'senhas_turismo@sme.novafriburgo.rj.gov.br'
email_pw: ''
hCAPTCHA_Public_Key: ''
hCAPTCHA_Secret_Key: ''
GOOGLE_OAUTH2_PUBLIC_KEY: ''
GOOGLE_OAUTH2_SECRET_KEY: ''
FACEBOOK_DEVELOPER_PUBLIC_KEY: ''
FACEBOOK_DEVELOPER_SECRET_KEY: ''
